apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: rd-2
  labels:
    role: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      labels:
        role: webserver
    spec:
      containers:
      - name: frontend
        image: httpd
        ports:
        - containerPort: 80
